name: flint_dart
description: A modern, expressive, and extensible server-side framework by Eulogia Technologies.
version: 1.0.0+21
homepage: https://flintdart.eulogia.net
repository: https://github.com/flint-dart/flint_dart
issue_tracker: https://github.com/flint-dart/flint_dart/issues
license: MIT

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  crypto: ^3.0.6       
  bcrypt: ^1.1.3        
  dart_jsonwebtoken: ^3.3.0  
  mysql_dart: ^1.2.1
  postgres: ^3.5.7
  mime: ^2.0.0
  uuid: ^4.5.1
  mailer: ^6.5.0
  package_config: ^2.2.0
  path: ^1.9.1
  universal_web: ^1.1.1+1
  flint_client: any



dev_dependencies:
  lints: ^5.0.0         # Dart lint rules
  test: ^1.24.0         # Testing framework

executables:
 flint: flint_dart
 hot_reload: hot_reload
