import 'dart:async';
import 'dart:convert';
import 'dart:js_interop';

import 'package:universal_web/web.dart' as web;

import 'browser_renderer.dart';
import 'component.dart';
import 'component_registry.dart';
import 'node.dart';
import 'style.dart';
import 'style_browser.dart';
import 'widgets.dart' hide FlintThemeController, flintTheme;
import 'widgets/shared/theme_controller.dart';

/// Intercepts page mounting before a Flint page component renders.
typedef FlintPageMiddleware = void Function(FlintPageContext context);

/// Resolves a page builder, optionally loading a deferred page library first.
typedef FlintAsyncPageBuilder =
    FutureOr<FlintPageBuilder?> Function(String component);

/// Server-provided page payload used to mount a Flint UI page.
class FlintPage {
  /// Registered component name to render.
  final String component;

  /// Props passed from the server to the page component.
  final Map<String, dynamic> props;

  /// Optional request URL associated with this page payload.
  final String? url;

  /// Optional page payload version.
  final String? version;

  /// Creates a page payload.
  const FlintPage({
    required this.component,
    this.props = const {},
    this.url,
    this.version,
  });

  /// Creates a page payload from decoded JSON.
  factory FlintPage.fromJson(Map<String, dynamic> json) {
    return FlintPage(
      component: json['component']?.toString() ?? '',
      props: _asStringKeyedMap(json['props']),
      url: json['url']?.toString(),
      version: json['version']?.toString(),
    );
  }
}

/// Context passed through page middleware before rendering.
class FlintPageContext {
  /// Creates middleware context for a page render.
  FlintPageContext({required this.host, required this.page});

  /// Host element that will receive the rendered page.
  final web.Element host;

  /// Page payload read from the host element.
  final FlintPage page;
  bool _stopped = false;

  /// Whether middleware has stopped page rendering.
  bool get stopped => _stopped;

  /// Stops page rendering after the current middleware returns.
  void stop() {
    _stopped = true;
  }
}

/// Fallback component rendered when a page name is not registered.
class MissingFlintPage extends StatelessComponent {
  /// Missing component name.
  final String component;

  /// Creates a fallback page for [component].
  MissingFlintPage(this.component);

  /// Builds the fallback missing-page message.
  @override
  FlintNode build() {
    return Container(
      props: {
        'style': {'padding': '24px', 'font-family': 'system-ui, sans-serif'},
      },
      children: [Text('Flint page "$component" was not registered.')],
    );
  }
}

/// Mounts a Flint UI app into the element matching [selector].
///
/// The host element must contain a `data-flint-page` payload generated by
/// FlintDart's page response helpers.
void createFlintApp(
  String selector, {
  Map<String, FlintPageBuilder>? pages,
  PageRegistry? registry,
  FlintAsyncPageBuilder? resolvePage,
  List<FlintPageMiddleware> middlewares = const [],
  List<StyleSheet> stylesheets = const [],
  FlintTheme? theme,
  FlintThemeProvider? themeProvider,
  FlintThemeMode? themeMode,
  RootDesign? rootDesign,
  FlintComponent Function(String component)? missingPage,
}) {
  final host = web.document.querySelector(selector);

  if (host == null) {
    throw StateError('No element found for selector "$selector".');
  }

  final initialThemeMode = _initialAppThemeMode(
    themeProvider: themeProvider,
    themeMode: themeMode,
    rootDesign: rootDesign,
  );
  if (initialThemeMode != null && host.getAttribute('data-theme') == null) {
    host.setAttribute('data-theme', initialThemeMode.value);
  }
  if (initialThemeMode != null) {
    flintTheme.configure(initialMode: initialThemeMode, target: host);
  }

  registerRootDesign(
    RootDesign(
      name: 'flint-animations',
      keyframes: [
        StyleKeyframes.spin(),
        StyleKeyframes.fadeIn(),
        StyleKeyframes.slideUp(),
        StyleKeyframes.slideDown(),
        StyleKeyframes.scaleIn(),
      ],
    ),
  );

  final appTheme = _appThemeRootDesign(
    theme: theme,
    themeProvider: themeProvider,
    themeMode: themeMode,
  );
  if (appTheme != null) {
    registerRootDesign(appTheme);
  }

  if (rootDesign != null) {
    registerRootDesign(rootDesign);
  }

  for (final stylesheet in stylesheets) {
    registerStyleSheet(stylesheet);
  }

  final page = _readPage(host);
  final root = createRootForElement(host);
  var navigationRequest = 0;

  Future<void> renderPage(FlintPage page, int requestId) async {
    final context = FlintPageContext(host: host, page: page);

    for (final middleware in middlewares) {
      middleware(context);
      if (context.stopped) return;
    }

    final builder =
        registry?[page.component] ??
        pages?[page.component] ??
        await resolvePage?.call(page.component);

    if (requestId != navigationRequest) return;

    if (builder == null && missingPage == null) {
      throw StateError('Flint page "${page.component}" was not registered.');
    }

    final component =
        builder?.call(page.props) ?? missingPage!.call(page.component);

    root.render(component);
  }

  Future<void> renderCurrentLocation() async {
    final requestId = ++navigationRequest;
    try {
      final next = await _fetchPageForCurrentLocation(selector);
      if (requestId != navigationRequest) return;
      host.setAttribute('data-flint-page', jsonEncode(next.page));
      if (next.title != null && next.title!.isNotEmpty) {
        web.document.title = next.title!;
      }
      await renderPage(FlintPage.fromJson(next.page), requestId);
    } catch (_) {
      web.window.location.assign(
        '${web.window.location.pathname}${web.window.location.search}',
      );
    }
  }

  unawaited(renderPage(page, navigationRequest));
  web.window.addEventListener(
    'flint:navigate',
    ((web.Event _) {
      renderCurrentLocation();
    }).toJS,
  );
  web.window.addEventListener(
    'popstate',
    ((web.Event _) {
      renderCurrentLocation();
    }).toJS,
  );
}

RootDesign? _appThemeRootDesign({
  FlintTheme? theme,
  FlintThemeProvider? themeProvider,
  FlintThemeMode? themeMode,
}) {
  if (themeProvider != null || themeMode != null) {
    final provider = themeProvider == null
        ? FlintThemeProvider(initialMode: themeMode ?? FlintThemeMode.light)
        : FlintThemeProvider(
            light: themeProvider.light,
            dark: themeProvider.dark,
            initialMode: themeMode ?? themeProvider.initialMode,
          );

    return RootDesign(name: 'flint-theme', themeProvider: provider);
  }

  if (theme != null) {
    return RootDesign(name: 'flint-theme', theme: theme);
  }

  return null;
}

FlintThemeMode? _initialAppThemeMode({
  FlintThemeProvider? themeProvider,
  FlintThemeMode? themeMode,
  RootDesign? rootDesign,
}) {
  if (themeMode != null) return themeMode;
  if (themeProvider != null) return themeProvider.initialMode;
  return rootDesign?.themeProvider?.initialMode;
}

FlintPage _readPage(web.Element host) {
  final encoded = host.getAttribute('data-flint-page');

  if (encoded == null || encoded.trim().isEmpty) {
    throw StateError('Missing data-flint-page payload on Flint app root.');
  }

  final decoded = jsonDecode(encoded);

  if (decoded is! Map<String, dynamic>) {
    throw StateError('Invalid Flint page payload.');
  }

  return FlintPage.fromJson(decoded);
}

Map<String, dynamic> _asStringKeyedMap(Object? value) {
  if (value is Map<String, dynamic>) return value;

  if (value is Map) {
    return value.map((key, entryValue) => MapEntry(key.toString(), entryValue));
  }
  return const {};
}

Future<_FetchedFlintPage> _fetchPageForCurrentLocation(String selector) {
  final url = '${web.window.location.pathname}${web.window.location.search}';
  final xhr = web.XMLHttpRequest();
  final completer = Completer<_FetchedFlintPage>();

  xhr.open('GET', url, true);
  xhr.setRequestHeader('Accept', 'text/html');

  xhr.onLoad.listen((_) {
    if (xhr.status < 200 || xhr.status >= 300) {
      completer.completeError(StateError('HTTP ${xhr.status}'));
      return;
    }

    try {
      completer.complete(_parseFetchedPage(xhr.responseText, selector));
    } catch (error) {
      completer.completeError(error);
    }
  });

  xhr.onError.listen((_) {
    completer.completeError(StateError('Navigation request failed.'));
  });

  xhr.send();
  return completer.future;
}

_FetchedFlintPage _parseFetchedPage(String html, String selector) {
  final container = web.document.createElement('div');
  container.innerHTML = html.toJS;
  final host =
      container.querySelector(selector) ??
      container.querySelector('[data-flint-page]');
  final encoded = host?.getAttribute('data-flint-page');

  if (encoded == null || encoded.trim().isEmpty) {
    throw StateError('Missing data-flint-page payload in fetched page.');
  }

  final decoded = jsonDecode(encoded);
  if (decoded is! Map<String, dynamic>) {
    throw StateError('Invalid fetched Flint page payload.');
  }

  return _FetchedFlintPage(page: decoded, title: _titleFromHtml(html));
}

String? _titleFromHtml(String html) {
  final match = RegExp(
    r'<title[^>]*>(.*?)</title>',
    caseSensitive: false,
    dotAll: true,
  ).firstMatch(html);
  if (match == null) return null;
  return _decodeHtmlText(match.group(1) ?? '').trim();
}

String _decodeHtmlText(String value) {
  final element = web.document.createElement('textarea');
  element.innerHTML = value.toJS;
  return element.textContent ?? value;
}

class _FetchedFlintPage {
  _FetchedFlintPage({required this.page, required this.title});

  final Map<String, dynamic> page;
  final String? title;
}
